// Generated by CoffeeScript 1.8.0
var plotChart, plotFacultyAverage, plotFacultyHighest;

plotChart = function(container, data, label_func, href_func, label, value) {
  var bars, chart, header;
  chart = d3.select(container);
  header = chart.append("li").attr("class", "header");
  header.append("a").text(label);
  header.append("label").text(value);
  bars = chart.selectAll("li.bar").data(data.values).enter().append("li").attr("class", "bar");
  bars.append("span").style("width", function(d) {
    return parseInt(d.value) / data.max * 100 + "%";
  }).append("a").attr("href", href_func).text(label_func);
  return bars.append("label").text(function(d) {
    return "$" + accounting.formatNumber(d.value);
  });
};

plotFacultyAverage = function() {
  return d3.json("http://ubyssey.ca/wp-content/themes/theme/snippets/charts/salaries/faculty_average.json", function(error, json) {
    return plotChart('.faculty-average', json, function(d) {
      return d.faculty;
    }, function(d) {
      return "http://ubyssey.ca/salaries/search?faculty_id=" + d.id;
    }, 'Faculty', 'Average Salary');
  });
};

plotFacultyHighest = function() {
  return d3.json("http://ubyssey.ca/wp-content/themes/theme/snippets/charts/salaries/faculty_highest.json", function(error, json) {
    return plotChart('.faculty-highest', json, function(d) {
      return d.employee + " (" + d.faculty + ")";
    }, function(d) {
      return "http://ubyssey.ca/salaries/employee/" + d.url;
    }, 'Employee', 'Salary');
  });
};

plotFacultyAverage();

plotFacultyHighest();
